name: Build with Gradle
description: A collection of actions for building Gradle projects, as well as generating a dependency graph via Dependency Submission.

runs:
  using: "composite"
  steps:
  - run: |
      echo "::error::The path 'mateherber-jt/gradle-actions' is not a valid action. Please use 'mateherber-jt/gradle-actions/setup-gradle' or 'mateherber-jt/gradle-actions/dependency-submission'."
      exit 1
    shell: bash

branding:
  icon: 'box'
  color: 'gray-dark'
