name: Combine Bot PRs

on:
  workflow_dispatch:

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-wrapperbot-prs:
    if: github.repository == 'gradle/actions'
    runs-on: ubuntu-latest
    steps:
      - name: combine-wrapperbot-prs
        uses: github/combine-prs@v5.2.0
        with:
          branch_prefix: wrapperbot
          pr_title: 'Bump Gradle Wrappers'
          ci_required: "false"
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
