name: Combine Bot PRs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  combine-wrapperbot-prs:
    permissions:
      contents: write
      pull-requests: write
      checks: read
    if: github.repository == 'gradle/actions'
    runs-on: ubuntu-latest
    steps:
      - name: combine-wrapperbot-prs
        uses: github/combine-prs@2909f404763c3177a456e052bdb7f2e85d3a7cb3 # v5.2.0
        with:
          branch_prefix: wrapperbot
          combine_branch_name: wrapperbot/combined-wrapper-updates
          pr_title: 'Bump Gradle Wrappers'
          ci_required: "false"
