name: CI-init-script-check

on:
  push:
    branches:
    - 'main'
    - 'release/**'
    paths-ignore:
    - 'dist/**'
  pull_request:
    paths:
      - '.github/workflows/ci-init-script-check.yml'
      - 'sources/src/resources/init-scripts/**'
      - 'sources/test/init-scripts/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-init-scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Java
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # Use a released version to avoid breakages
      env:
        ALLOWED_GRADLE_WRAPPER_CHECKSUMS: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 # Invalid wrapper jar used for testing
    - name: Run integration tests
      working-directory: sources/test/init-scripts
      run: ./gradlew check
