name: CI-update-dist

on:
  workflow_dispatch:
  push:
    branches:
    - 'prerelease/**'
    - 'release/**'
    paths-ignore:
    - 'dist/**'

permissions:
  contents: read

concurrency:
  group: update-dist-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-dist:
    # Only update dist in our maintained repository.
    if: github.repository == 'jobandtalent/gradle-actions'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: sources/package-lock.json

    - name: Install npm dependencies
      run: |
        npm clean-install
      working-directory: sources

    - name: Build distribution
      run: |
        npm run check
        npm run compile
      working-directory: sources

    - name: Copy the generated sources/dist directory to the top-level dist
      run: |
        cp -r sources/dist .

    # Commit and push changes; has no effect if the files did not change
    # Important: The push event will not trigger any other workflows, see
    # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
    - name: Commit & push changes
      uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
      with:
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_message: '[bot] Update dist directory'
        file_pattern: dist
